const sharePointFolderURL = "https://ingredientsonline1.sharepoint.com/:f:/s/SellerDocuments/IgBsXbXqZGdyTqUeXHN6-MrrAUdL65lg9aA148uTQ9eabVo?e=h3Hksl";
const scenario={amount:10108.60,correct:{pipeline:'Seller Programs',dealStage:'Quote Sent to Prospect',forecast:'Pipeline',program:'Seller Direct',subscription:'Growth'},options:{pipeline:['Seller Programs','Seller Marketing Services','Seller Services','Sales Online NSM','Sales Online Plus NSM','Sample Order Opportunities'],dealStage:['Initial Outreach Successful','Discovery Meeting Scheduled','Discovery Meeting Completed','Quote Sent to Prospect','Contract Issued - Pending Signature','Contract Signed','1st Payment Collected','QC Approval Pending','QC Approved / Pending 2nd Payment','2nd Payment Collected','Closed Won','Closed Lost','VA/Pending Product Approval','VA/Product Approved','VA/QC Approval Pending','VA/Product Rejected'],forecast:['Not Forecasted','Pipeline','Best Case','Commit','Closed Won'],program:['Seller Direct','Dropship','IO Connect'],subscription:['Starter','Growth','Pro']}};
const $=id=>document.getElementById(id),required=['dealName','pipeline','dealStage','forecast','program','subscription','amount','notes','contact','meeting'];let participant='',startedAt,deadline,timer,expired=false,resultDate;
const scores=[['Deal Name','dealName',5],['Pipeline','pipeline',10],['Deal Stage','dealStage',10],['Forecast Category','forecast',10],['Program','program',10],['Subscription','subscription',10],['Amount','amount',20],['Deal Notes','notes',10],['Contact Associated','contact',5],['Meeting Associated','meeting',5],['Submit Simulation','submit',5]];
function time(s){return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}function money(v){return Number(String(v).replace(/[$,\s]/g,''))}function addActivity(t){const e=document.createElement('li');e.innerHTML=`<time>${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time>${t}`;$('activityFeed').prepend(e)}function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;$('toastRegion').append(e);setTimeout(()=>e.remove(),3200)}function noteValid(v){const t=String(v).toLowerCase().replace(/,/g,'');return t.includes('growth')&&t.includes('annual')&&t.includes('10108.6')}
function wrap(id){return $(id).closest('.field')||$(id).closest('.assoc')}function clear(id){const w=wrap(id);w.classList.remove('invalid');w.querySelector('.field-error')?.remove()}function error(id,text){const w=wrap(id);w.classList.add('invalid');let e=w.querySelector('.field-error');if(!e){e=document.createElement('small');e.className='field-error';w.append(e)}e.textContent=text}function progress(){const n=required.filter(id=>$(id).type==='checkbox'?$(id).checked:$(id).value.trim()).length,p=Math.round(n/required.length*100);$('progressBar').style.width=`${p}%`;$('progressText').textContent=`${p}% complete`}
function tick(){const r=Math.max(0,Math.ceil((deadline-Date.now())/1000));$('timer').textContent=time(r);if(!r&&!expired){expired=true;clearInterval(timer);$('timeExpired').classList.remove('hidden');addActivity('Time limit reached - simulation continues');toast('Time has expired. You may continue.')}}
function begin(){participant=$('participantName').value.trim();if(!participant||!$('disclaimer').checked){$('welcomeError').textContent='Enter your name and confirm that you understand the instructions to begin.';return}$('participantLabel').textContent=participant;$('welcomeScreen').classList.add('hidden');$('briefingScreen').classList.remove('hidden');startedAt=Date.now();deadline=startedAt+600000;timer=setInterval(tick,1000);tick();addActivity('Simulation started');toast('Simulation started')}
function openWorkspace(){$('briefingScreen').classList.add('hidden');$('simulatorScreen').classList.remove('hidden');$('dealName').focus()}
function validateRequired(){let first;required.forEach(clear);required.forEach(id=>{const e=$(id),valid=e.type==='checkbox'?e.checked:e.value.trim();if(!valid){error(id,e.type==='checkbox'?'Association required.':'This property is required.');first??=e}});return first}
function calculate(){const e={dealName:$('dealName').value.trim()?5:0,pipeline:$('pipeline').value===scenario.correct.pipeline?10:0,dealStage:$('dealStage').value===scenario.correct.dealStage?10:0,forecast:$('forecast').value===scenario.correct.forecast?10:0,program:$('program').value===scenario.correct.program?10:0,subscription:$('subscription').value===scenario.correct.subscription?10:0,amount:Math.abs(money($('amount').value)-scenario.amount)<.001?20:0,notes:noteValid($('notes').value)?10:0,contact:$('contact').checked?5:0,meeting:$('meeting').checked?5:0,submit:5};return{e,total:Object.values(e).reduce((a,b)=>a+b,0)}}
function hints(){Object.entries(scenario.correct).forEach(([id,v])=>{if($(id).value!==v)error(id,`For this scenario, select “${v}”.`)});if(Math.abs(money($('amount').value)-scenario.amount)>.001)error('amount','Remember to include the onboarding fee.');if(!noteValid($('notes').value))error('notes','Document Growth Subscription, annual billing, and $10,108.60.')}
function complete(e){e.preventDefault();const first=validateRequired();if(first){$('formMessage').textContent='Please complete the highlighted properties before submitting.';first.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>first.focus(),300);return}hints();clearInterval(timer);addActivity('Simulation submitted');toast('Simulation submitted');setTimeout(results,300)}
function responseData(){return[['Deal Name',$('dealName').value.trim(),'dealName'],['Pipeline',$('pipeline').value,'pipeline'],['Deal Stage',$('dealStage').value,'dealStage'],['Forecast Category',$('forecast').value,'forecast'],['Program',$('program').value,'program'],['Subscription',$('subscription').value,'subscription'],['Amount',$('amount').value,'amount'],['Deal Notes',$('notes').value,'notes'],['Contact Associated',$('contact').checked?'Yes':'No','contact'],['Meeting Associated',$('meeting').checked?'Yes':'No','meeting']]}
function results(){const r=calculate(),pass=r.total>=80;resultDate=new Date();$('simulatorScreen').classList.add('hidden');$('completionScreen').classList.remove('hidden');$('resultName').textContent=participant;$('resultDate').textContent=resultDate.toLocaleDateString([],{year:'numeric',month:'long',day:'numeric'});$('resultTime').textContent=time(Math.round((Date.now()-startedAt)/1000));$('resultScore').textContent=`${r.total}%`;$('resultStatus').textContent=pass?'Passed':'Needs Coaching';$('resultStatus').className=pass?'passed':'coaching';const answers=responseData();$('responseList').innerHTML=answers.map(([n,v])=>`<div><dt>${n}</dt><dd>${v||'Not provided'}</dd></div>`).join('');const correct=answers.filter(([, ,key])=>r.e[key]===scores.find(x=>x[1]===key)[2]).map(([n])=>n);const improve=answers.filter(([, ,key])=>r.e[key]!==scores.find(x=>x[1]===key)[2]).map(([n])=>n);$('correctResponses').textContent=correct.join(', ')||'None';$('improveResponses').textContent=improve.join(', ')||'None'}
function file(){const n=participant.replace(/[^a-z0-9]+/gi,'_').replace(/^_|_$/g,'')||'Participant',d=(resultDate||new Date()).toISOString().slice(0,10);return`SBD_Simulator_${n}_${d}`}function download(){const prior=document.title;document.title=file();window.print();setTimeout(()=>document.title=prior,1200)}function reset(){clearInterval(timer);$('dealForm').reset();$('completionScreen').classList.add('hidden');$('briefingScreen').classList.add('hidden');$('welcomeScreen').classList.remove('hidden');$('participantName').value='';$('disclaimer').checked=false;$('activityFeed').innerHTML='';$('progressBar').style.width='0';$('progressText').textContent='0% complete';$('timer').textContent='10:00';$('timeExpired').classList.add('hidden');$('formMessage').textContent='';expired=false;required.forEach(clear);scrollTo(0,0)}
Object.entries(scenario.options).forEach(([id,items])=>items.forEach(v=>$(id).add(new Option(v,v))));$('startBtn').onclick=begin;$('openWorkspaceBtn').onclick=openWorkspace;$('dealForm').onsubmit=complete;$('restartBtn').onclick=reset;$('downloadBtn').onclick=download;$('submitResultsBtn').onclick=()=>window.open(sharePointFolderURL,'_blank','noopener');required.forEach(id=>{const e=$(id);e.oninput=()=>{clear(id);progress()};e.onchange=()=>{clear(id);progress();if(e.tagName==='SELECT'&&e.value){addActivity(`${e.previousElementSibling.textContent.replace('*','').trim()} selected`);toast('Deal updated')}if(e.type==='checkbox'&&e.checked){addActivity(id==='contact'?'Contact associated':'Meeting associated');toast('Association updated')}}});$('amount').onblur=()=>{if($('amount').value&&!Number.isNaN(money($('amount').value)))$('amount').value=money($('amount').value).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})};
